// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "https://gitee.com/openeuler/KubeMate",
            "url": "https://gitee.com/openeuler/KubeMate",
            "email": "https://gitee.com/openeuler/KubeMate"
        },
        "license": {
            "name": "Mulan PSL v2",
            "url": "http://license.coscl.org.cn/MulanPSL2"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clusterconfig/upload": {
            "post": {
                "description": "Upload a file with optional description",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "集群配置文件"
                ],
                "summary": "Upload a cluster config file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "The cluster config file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "k8s name",
                        "name": "cluster_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The type of the uploaded file (e.g., 'crfile', 'configfile')",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The JSON string containing labels for the uploaded file",
                        "name": "labels",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proto.FileResult"
                        }
                    }
                }
            }
        },
        "/clusterconfig/{cluster_id}": {
            "get": {
                "description": "Query a clusterconfig file by cluster ID",
                "tags": [
                    "集群配置文件"
                ],
                "summary": "Query a clusterconfig file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "k8s cluster ID",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/proto.FileResult"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a cluster config file with optional description",
                "tags": [
                    "集群配置文件"
                ],
                "summary": "Delete a cluster config file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "k8s name",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - Indicates successful deletion"
                    }
                }
            }
        },
        "/kubeconfig/upload": {
            "post": {
                "description": "Upload a file with optional description",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kubeconfig文件"
                ],
                "summary": "Upload a kubeconfig file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "The kubeconfig file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "k8s name",
                        "name": "cluster_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful file upload",
                        "schema": {
                            "$ref": "#/definitions/proto.FileResult"
                        }
                    }
                }
            }
        },
        "/kubeconfig/{cluster_id}": {
            "get": {
                "description": "Query a kubeconfig file by cluster ID",
                "tags": [
                    "kubeconfig文件"
                ],
                "summary": "Query a kubeconfig file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "k8s cluster ID",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - Indicates successful get"
                    }
                }
            },
            "delete": {
                "description": "Delete a file with optional description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kubeconfig文件"
                ],
                "summary": "Delete a kubeconfig file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "k8s name",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - Indicates successful deletion"
                    }
                }
            }
        }
    },
    "definitions": {
        "proto.FileResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "0.0.0.0:9090",
	BasePath:         "/swagger/index.html",
	Schemes:          []string{},
	Title:            "统一运维入口",
	Description:      "接受运维管理平台的请求，进行os以云原生的方式进行升级",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
